import os
os.chdir("C:/Users/ssdsk/projects/SOCOM")
content = []
content.append("---")
content.append('title: "SOCOM Tactical Shooter - Product Requirements Document"')
content.append('version: "3.0.0"')
content.append('date: "2026-06-19"')
content.append('author: "Sam / Quicksilver"')
content.append('status: "Active - Phase 2 Complete, Pre-Asset"')
content.append("---")
content.append("")
content.append("# Product Requirements Document")
content.append("")
content.append("## 1. Executive Summary")
content.append("")
content.append("SOCOM Tactical Shooter is a modern reimagining of the classic PS2 tactical")
content.append("shooter rebuilt for PC with AAA production values using Rust and Bevy 0.18.1.")
content.append("It targets authentic squad-based tactical combat inspired by Arma 3, Squad,")
content.append("and Ghost Recon - with combined 1st/3rd person perspectives, an 8-component")
content.append("modular weapon system, deep gear progression, drone warfare, AI teammates,")
content.append("and competitive multiplayer modes.")
content.append("")
content.append("Current Status: All core gameplay systems implemented (91 source files,")
content.append("0 errors). Pre-asset - awaiting audio, 3D models, VFX.")
content.append("")
content.append("Development Philosophy: Enterprise arch with zero Bevy dep in core crate,")
content.append("message-driven communication, single-responsibility files, systems built")
content.append("complete before asset integration.")
content.append("")
content.append("## 2. Target Audience & Personas")
content.append("")
content.append("| Persona | Description | Goals |")
content.append("|---------|-------------|-------|")
content.append("| SOCOM Veteran (Primary) | Age 30-45, played original SOCOM on PS2 | Over-shoulder cam, squad commands, nostalgia |")
content.append("| Tactical Shooter Fan (Primary) | Arma, Squad, Hell Let Loose | Real movement, suppression, stamina, weapon weight |")
content.append("| Competitive Player (Secondary) | R6 Siege, CS2 | Round-based, ranked, weapon balance |")
content.append("| Casual Player (Secondary) | Limited time, pick-up-and-play | Training range, bot matches, simple controls |")
content.append("| MilSim Enthusiast (Tertiary) | Authentic military sim | Real ballistics, gear weight, team coordination |")
content.append("| Modder (Tertiary) | Create custom content | GLTF maps, RON configs, documentation |")
content.append("| Developer/Contributor | Open source | Clean arch, CI/CD, test coverage |")
content.append("| Content Creator | Streams/YT | Spectator mode, replay, cinematic tools |")
content.append("")
content.append("## 3. Comprehensive User Stories")
content.append("")
content.append("### Movement & Controls")
content.append("- As a SOCOM veteran, I want over-shoulder cam with shoulder swap for authentic feel.")
content.append("- As an Arma player, I want 1st/3rd person toggle with keybind.")
content.append("- As a tactical fan, I want realistic stance transitions (0.3s crouch, 0.8s prone).")
content.append("- As a competitive player, I want responsive controls with no input lag.")
content.append("- As a disabled player, I want fully rebindable controls and adjustable sensitivity.")
content.append("- As a MilSim fan, I want weapon weight to affect movement and turn rate.")
content.append("- As a speedrunner, I want consistent deterministic physics.")
content.append("")
content.append("### Combat & Weapons")
content.append("- As a tactical fan, I want hitscan weapons with realistic damage values.")
content.append("- As a SOCOM vet, I want visible weapon model in 1st/3rd person with muzzle flash.")
content.append("- As a gun enthusiast, I want modular weapons (barrel/sight/grip/mag/stock) with real stat tradeoffs.")
content.append("- As a competitive player, I want weapon balance and clear TTK values.")
content.append("- As a MilSim fan, I want ammo types (FMJ/HP/AP/Tracer) with different behaviours.")
content.append("- As a player, I want clear hip-fire vs ADS differences.")
content.append("- As a modder, I want weapons in RON config files for custom guns.")
content.append("")
content.append("### Health & Damage")
content.append("- As a tactical fan, I want no health regen - damage permanent until medic.")
content.append("- As a player, I want visual damage feedback (vignette, sound, direction indicator).")
content.append("- As a MilSim fan, I want limb damage multipliers (headshot=instant kill).")
content.append("- As a player, I want suppression to blur vision and increase weapon sway.")
content.append("")
content.append("### AI & Teammates")
content.append("- As a SOCOM vet, I want command wheel: Move, Engage, Suppress, Regroup.")
content.append("- As a single-player fan, I want competent AI teammates that take cover and revive.")
content.append("- As a player, I want enemies with vision cones, patrol routes, suppression reactions.")
content.append("- As a casual player, I want fair AI - not aimbotting, not brain-dead.")
content.append("")
content.append("### Drones & Equipment")
content.append("- As a modern warfare fan, I want Recon UAV for scouting and FPV Strike for attacks.")
content.append("- As a player, I want intuitive camera-relative drone controls, battery management.")
content.append("- As a MilSim fan, I want realistic flight characteristics and limited battery.")
content.append("")
content.append("### Progression & Gear")
content.append("- As an RPG fan, I want XP, leveling, unlockable weapons and attachments.")
content.append("- As a player, I want achievements for skill - headshots, killstreaks, perfection.")
content.append("- As a tactical fan, I want specializations (Assault/Medic/Engineer/Recon) with real impact.")
content.append("- As a completionist, I want collectible weapons/gear with 5 rarities.")
content.append("- As a player, I want gear to matter - armour reduces damage, weapons kill faster.")
content.append("")
content.append("### Game Modes")
content.append("- As a competitive player, I want TDM (5v5, no-respawn, first to 5 rounds).")
content.append("- As a tactical fan, I want Demolition (attack/defend bomb, halftime switch).")
content.append("- As a SOCOM vet, I want CTF (1-life, capture flag OR eliminate all).")
content.append("- As a casual player, I want Training Range (any weapon, static/moving targets).")
content.append("- As a solo player, I want Single Player + Bots in all modes.")
content.append("- As a player, I want 5-6 min rounds, best-of-9 (first to 5 wins).")
content.append("- As a viewer, I want clear win conditions shown prominently.")
content.append("")
content.append("### Multiplayer & Networking")
content.append("- As a competitive player, I want dedicated servers with low-latency netcode.")
content.append("- As a party player, I want squad up with friends, lobbies, voice chat.")
content.append("- As a player, I want skill-based matchmaking and persistent profile (K/D, wins, rank).")
content.append("")
content.append("### UI & Experience")
content.append("- As a player, I want clean HUD (health, stamina, ammo, stance, crosshair) without clutter.")
content.append("- As a new player, I want tutorial for movement, shooting, squad, drones.")
content.append("- As a player, I want main menu: Play, Training, Loadout, Settings.")
content.append("- As a player, I want video/audio/controls settings screens.")
content.append("- As a player, I want kill feed, damage vignette, XP popups for feedback.")
content.append("")
content.append("### Performance & Technical")
content.append("- As a developer, I want 0 errors and clean clippy at all times.")
content.append("- As a mid-range PC player, I want 60+ FPS at 1080p.")
content.append("- As a speedrunner, I want deterministic 120Hz fixed timestep physics.")
content.append("- As a modder, I want clean separation between engine and gameplay code.")
content.append("")
content.append("## 4. Game Modes")
content.append("")
content.append("### 4.1 Training Range")
content.append("| Property | Value |")
content.append("|----------|-------|")
content.append("| Players | 1 (solo) |")
content.append("| Time Limit | Unlimited |")
con
